[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv"]

[phases.install]
cmds = ["python3.12 -m pip install --upgrade pip", "python3.12 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3.12 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
