[phases.setup]
nixPkgs = ["python313", "gcc", "gnumake"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu",
    "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn ai:app --host 0.0.0.0 --port $PORT"
